version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      APP_DEBUG: 'true'
      PHP_IDE_CONFIG: "serverName=docker"
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - magento-network

  webserver:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/config/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - app
      - db
    networks:
      - magento-network

  db:
    image: mysql:5.7.24
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: magento
      MYSQL_ROOT_PASSWORD: root
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    volumes:
      - dbdata:/var/lib/mysql
      - ./docker/config/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - magento-network

  elasticsearch:
    image: elasticsearch:7.9.3
    environment:
        - cluster.name=docker-cluster
        - bootstrap.memory_lock=true
        - discovery.type=single-node
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
        memlock:
            soft: -1
            hard: -1
    volumes:
        - elasticsearchdata:/usr/share/elasticsearch/data
    ports:
        - 9200:9200
    networks:
        - magento-network

networks:
  magento-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
  elasticsearchdata:
    driver: local

